### ISSUE TITLE
When i restart server, the plugin will error and not working again

### ISSUE THREAD

**Issue by azhimmanru** [vecnavium-pm-pl/VecnaLeaderboards#44]
When i restart server, the plugin will error and not working again

**Comment by Vecnavium** [comment]
⚠️ This issue ticket doesn't have all the required information ⚠️
To make it as quick and easy as possible for us to fix your problem, an issue template is provided which lists certain required information. 

Please respond to the questions provided in the issues template when you went to create this issue tp help us to help you by providing the information we asked for.
