### ISSUE TITLE
Its a Plugin idea or reproduce for ApI4

### ISSUE THREAD

**Issue by DragonfireHD** [vecnavium-pm-pl/VecnaLeaderboards#48]
Can you maybe fix or create a new PerworldPlayer Plugin for different World Options ? 

I now that idea is not for Leaderboards but PerWorldPlayer is a important Plugin what all User need for  Worlds with different MiniGames wit different Inventories

**Comment by Vecnavium** [comment]
This isn't the place to ask for a fix of PerWorldPlayer go to their repository and create an issue there asking them what you need
