### ISSUE TITLE
/lb manage Command Crashed my Server :D

### ISSUE THREAD

**Issue by DragonfireHD** [vecnavium-pm-pl/VecnaLeaderboards#49]
[22:09:03.353] [Server thread/INFO]: [+] NemesisFire2348

[22:10:15.855] [Server thread/CRITICAL]: Error: "Call to a member function getMessage() on null" (EXCEPTION) in "plugins/VecnaLeaderboards_dev-356.phar/src/Vecnavium/VecnaLeaderboards/Commands/LeaderboardCommand" at line 60

--- Stack trace ---

#0 pmsrc/src/command/SimpleCommandMap(220): Vecnavium\VecnaLeaderboards\Commands\LeaderboardCommand->execute(object ipad54\netherblocks\player\Player#98830, string[8] lbmanage, array[0])

#1 pmsrc/src/Server(1406): pocketmine\command\SimpleCommandMap->dispatch(object ipad54\netherblocks\player\Player#98830, string[9] lbmanage )

#2 pmsrc/src/player/Player(1337): pocketmine\Server->dispatchCommand(object ipad54\netherblocks\player\Player#98830, string[9] lbmanage )

#3

**Comment by JavierLeon9966** [comment]
Can you stop using dev builds? You should know that dev builds can be unstable and prone to errors so that’s expected. You should use a released version of the plugin

**Comment by Vecnavium** [comment]
Hi, this issue has been fixed in this release. https://github.com/vecnavium-pm-pl/VecnaLeaderboards/releases/tag/v2.1.4
