### ISSUE TITLE
Command not existing 

### ISSUE THREAD

**Issue by Tuvqlu** [vecnavium-pm-pl/VecnaLeaderboards#51]
**Describe the bug**
/leaderboard command does not exist in game:

**Expected behavior**
The command to work 
**VecnaLeaderboards plugin information**
2.1.3 version 

**Screenshots**

.

**Comment by Vecnavium** [comment]
Insufficient details, wrong issue description & false issue.
The command does exist but it has an issue and there will be a fix for it soon.
