### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by GamerMJay** [vecnavium-pm-pl/VecnaLeaderboards#53]
[15:31:33.771] [Server thread/CRITICAL]: pocketmine\utils\AssumptionFailedError: "Position world is null or has been unloaded" (EXCEPTION) in "pmsrc/src/world/Position" at line 70

--- Stack trace ---

#0 plugins/VecnaLeaderboards.phar/src/Vecnavium/VecnaLeaderboards/Leaderboard/Leaderboard(96): pocketmine\world\Position->getWorld()

#1 plugins/VecnaLeaderboards.phar/src/Vecnavium/VecnaLeaderboards/Leaderboard/Leaderboard(146): Vecnavium\VecnaLeaderboards\Leaderboard\Leaderboard->despawn()

#2 plugins/VecnaLeaderboards.phar/src/Vecnavium/VecnaLeaderboards/Main(69): Vecnavium\VecnaLeaderboards\Leaderboard\Leaderboard->__destruct()

#3 pmsrc/src/plugin/PluginBase(137): Vecnavium\VecnaLeaderboards\Main->onEnable()

#4 pmsrc/src/plugin/PluginManager(437): pocketmine\plugin\PluginBase->onEnableStateChange(true)

#5 pmsrc/src/Server(1385): pocketmine\plugin\PluginManager->enablePlugin(object Vecnavium\VecnaLeaderboards\Main#25261)

#6 pmsrc/src/Server(1006): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#24927)

#7 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/minecraft/, string[24] /home/minecraft/plugins/)

#8 pmsrc/src/PocketMine(327): pocketmine\server()

#9 pmsrc(11): require(string[57] phar:///home/minecraft/pocketmine.phar/src/PocketMine.php)

--- Previous ---

pocketmine\utils\AssumptionFailedError: "Position world is null or has been unloaded" (EXCEPTION) in "pmsrc/src/world/Position" at line 70

#0 plugins/VecnaLeaderboards.phar/src/Vecnavium/VecnaLeaderboards/Leaderboard/Leaderboard(78): pocketmine\world\Position->getWorld()

#1 plugins/VecnaLeaderboards.phar/src/Vecnavium/VecnaLeaderboards/Leaderboard/LeaderboardManager(55): Vecnavium\VecnaLeaderboards\Leaderboard\Leaderboard->spawn()

#2 plugins/VecnaLeaderboards.phar/src/Vecnavium/VecnaLeaderboards/Leaderboard/LeaderboardManager(48): Vecnavium\VecnaLeaderboards\Leaderboard\LeaderboardManager->registerLeaderboard(integer 1, string[5] kills, object pocketmine\world\Position#25544)

#3 plugins/VecnaLeaderboards.phar/src/Vecnavium/VecnaLeaderboards/Leaderboard/LeaderboardManager(39): Vecnavium\VecnaLeaderboards\Leaderboard\LeaderboardManager->loadLeaderboards()

#4 plugins/VecnaLeaderboards.phar/src/Vecnavium/VecnaLeaderboards/Main(69): Vecnavium\VecnaLeaderboards\Leaderboard\LeaderboardManager->__construct(object Vecnavium\VecnaLeaderboards\Main#25261)

#5 pmsrc/src/plugin/PluginBase(137): Vecnavium\VecnaLeaderboards\Main->onEnable()

#6 pmsrc/src/plugin/PluginManager(437): pocketmine\plugin\PluginBase->onEnableStateChange(true)

#7 pmsrc/src/Server(1385): pocketmine\plugin\PluginManager->enablePlugin(object Vecnavium\VecnaLeaderboards\Main#25261)

#8 pmsrc/src/Server(1006): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#24927)

#9 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/minecraft/, string[24] /home/minecraft/plugins/)

#10 pmsrc/src/PocketMine(327): pocketmine\server()

#11 pmsrc(11): require(string[57] phar:///home/minecraft/pocketmine.phar/src/PocketMine.php)

--- End of exception information ---

[15:31:33.771] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump

[15:31:33.775] [Server thread/EMERGENCY]: Please upload the "/home/minecraft/crashdumps/Wed_Feb_23-15.31.33-CET_2022.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

[15:31:33.775] [Server thread/EMERGENCY]: Forcing server shutdown

[15:31:33.775] [Server thread/INFO]: Disabling VecnaLeaderboards v2.1.4

[15:31:33.776] [Server thread/CRITICAL]: Error: "Call to a member function saveLeaderboards() on null" (EXCEPTION) in "plugins/VecnaLeaderboards.phar/src/Vecnavium/VecnaLeaderboards/Main" at line 85

--- Stack trace ---

#0 pmsrc/src/plugin/PluginBase(139): Vecnavium\VecnaLeaderboards\Main->onDisable()

#1 pmsrc/src/plugin/PluginManager(458): pocketmine\plugin\PluginBase->onEnableStateChange(false)

#2 pmsrc/src/plugin/PluginManager(447): pocketmine\plugin\PluginManager->disablePlugin(object Vecnavium\VecnaLeaderboards\Main#25261)

#3 pmsrc/src/Server(1444): pocketmine\plugin\PluginManager->disablePlugins()

#4 pmsrc/src/Server(1629): pocketmine\Server->forceShutdown()

#5 pmsrc/src/Server(1528): pocketmine\Server->crashDump()

#6 pmsrc/src/Server(1049): pocketmine\Server->exceptionHandler(object pocketmine\utils\AssumptionFailedError#25548)

#7 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/minecraft/, string[24] /home/minecraft/plugins/)

#8 pmsrc/src/PocketMine(327): pocketmine\server()

#9 pmsrc(11): require(string[57] phar:///home/minecraft/pocketmine.phar/src/PocketMine.php)

--- End of exception information ---

**Comment by Vecnavium** [comment]
This issue has been fixed on [this release](https://github.com/vecnavium-pm-pl/VecnaLeaderboards/releases/tag/v2.1.5)
