### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by logannn61** [vecnavium-pm-pl/VecnaLeaderboards#60]
/stats doesnt do anything
/leaderboard doesnt do anything
remove them from documentation
/lbmanage should be /lbcreate as it creates leaderboards and you cant remove them

**Comment by logannn61** [comment]
also server crash by doing /lbmanage delete
https://crash.pmmp.io/view/6162041

**Comment by Vecnavium** [comment]
/stats isn't even a command at all, it has been removed.
/leaderboard I will modify it from the readme.md
/lbmanage is the command that lets you manage all leaderboards such as create & delete

**Comment by Vecnavium** [comment]
> also server crash by doing /lbmanage delete https://crash.pmmp.io/view/6162041

What leaderboard type are you trying to delete?

**Comment by Vecnavium** [comment]
Documentation updated both Poggit & Github

**Comment by logannn61** [comment]
> /stats isn't even a command at all, it has been removed.

that is what I am saying remove it from the read me if it’s not a feature 
In features it says:
Being able to see others and your own player stats by using /stats

**Comment by logannn61** [comment]
> > also server crash by doing /lbmanage delete https://crash.pmmp.io/view/6162041
> 
> What leaderboard type are you trying to delete?

Kills

**Comment by Vecnavium** [comment]
This issue has been fixed and you can get the download for this fix from [this release](https://github.com/vecnavium-pm-pl/VecnaLeaderboards/releases/tag/v2.1.8)
