### ISSUE TITLE
Startup Bug

### ISSUE THREAD

**Issue by Krishvy** [vecnavium-pm-pl/VecnaLeaderboards#61]
**Describe the bug**
When I start my server, it crashes

**To Reproduce**
Steps to reproduce the behavior: Delete your world with a leaderboard in it

**Expected behavior**
No crash on startup
**VecnaLeaderboards plugin information**

- Plugin Version: Latest

**Screenshots**

**Additional context**
[12:49:49.986] [Server thread/CRITICAL]: Error: "Typed property Vecnavium\VecnaLeaderboards\Main::$leaderboardManager must not be accessed before initialization" (EXCEPTION) in "plugins/VecnaLeaderboards/src/Vecnavium/VecnaLeaderboards/Main" at line 85
--- Stack trace ---
  #0 pmsrc/src/plugin/PluginBase(139): Vecnavium\VecnaLeaderboards\Main->onDisable()
  #1 pmsrc/src/plugin/PluginManager(459): pocketmine\plugin\PluginBase->onEnableStateChange(false)
  #2 pmsrc/src/plugin/PluginManager(448): pocketmine\plugin\PluginManager->disablePlugin(object Vecnavium\VecnaLeaderboards\Main#25086)
  #3 pmsrc/src/Server(1444): pocketmine\plugin\PluginManager->disablePlugins()
  #4 pmsrc/src/Server(1629): pocketmine\Server->forceShutdown()
  #5 pmsrc/src/Server(1528): pocketmine\Server->crashDump()
  #6 pmsrc/src/Server(1049): pocketmine\Server->exceptionHandler(object pocketmine\utils\AssumptionFailedError#30026)
  #7 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #8 pmsrc/src/PocketMine(327): pocketmine\server()
  #9 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---
[12:49:49.986] [Server thread/EMERGENCY]: Crashed while crashing, killing process

**Comment by Vecnavium** [comment]
Fixed in latest PocketMine version and plugin version. https://github.com/vecnavium-pm-pl/VecnaLeaderboards/releases/tag/v2.2.1
