### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Tuvqlu** [vecnavium-pm-pl/VecnaLeaderboards#63]
**Describe the bug**
When I join my server it crashes

**To Reproduce**
Join Server with Plugin

**Expected behavior**
Leaderboards to appear
**VecnaLeaderboards plugin information**

- Plugin Version: Dev 381

**Additional context**
pocketmine\network\mcpe\protocol\AddPlayerPacket::create(): Argument #12 ($gameMode) must be of type int, array given, called in phar:///home/container/plugins/VecnaLeaderboards_dev-381 3.phar/src/Vecnavium/VecnaLeaderboards/Util/CustomFloatingText.php on line 86

**Comment by Zelurium** [comment]
Me too

**Comment by Vecnavium** [comment]
Fixed in the latest version https://github.com/vecnavium-pm-pl/VecnaLeaderboards/releases/tag/v2.2.0
